### ISSUE TITLE
aws-iam-authenticator is no longer required

### ISSUE THREAD

**Issue by dkeightley** [aws-samples/aws-lambda-layer-kubectl#1]
With the new 'aws eks get-token' command, and 'aws eks update-kubeconfig' now taking this approach it is worth reviewing if the aws-iam-authenticator binary is now needed in the layer. This would also reduce the size by ~26MB.

**Comment by dkeightley** [comment]
#2 for review

**Comment by pahud** [comment]
thanks for the PR but I also just committed  as well

https://github.com/aws-samples/aws-lambda-layer-kubectl/commit/7fa0bce22a711abf510c89aaa46e1b54d9e88a92
