### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [aws-samples/aws-lambda-layer-kubectl#10]
This seems useful, but it's not exactly clear how to use it. I would like to use this layer in a terraform lambda function that will deploy code to kubernetes. Deploying the layer into my AWS account was trivial, but using the layer in my lambda function doesn't seem to be working. If I don't specify a `bootstrap`, the lambda will complain:

```
RequestId: 2937336c-0003-4166-afac-a24fbd14a853 Error: &{0xc00005e2a0 map[error:Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap] invoke_id:2937336c-0003-4166-afac-a24fbd14a853 sandbox_id:18] 2019-10-14 00:08:25.212580839 +0000 UTC m=+0.081914915 panic <nil> Failed to locate runtime bootstrap <nil> }
Runtime.ExitError
```

Is the `bootstrap` not included in the layer? Would be nice to see directions similar to https://github.com/gkrizek/bash-lambda-layer#how-to.

**Comment by solarmosaic-kflorence** [comment]
It might also be useful to link to https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html -- since I was pretty lost before reading this.

**Comment by pahud** [comment]
Thanks for your valuable feedback. Will update the document to reflect this shortly.

**Comment by solarmosaic-kflorence** [comment]
Thanks @pahud 🙏

**Comment by pahud** [comment]
Actually I've tried both

kubectl in docker for CodeBuild is possible:
https://github.com/pahud/eks-kubectl-docker

The benefits using CodeBuild is you can just docker build image, pushing to ECR followed by deploying it all the way in the `buildspec.yml`.

Using lambda to deploy Kubernetes, on the other hand, would be much faster as it just usually takes less than 1 second to provision the lambda sandbox while CodeBuild could take a couple of seconds before it executes your kubectl command. And the cost could be yet anther concern.

However, if those are not your primary concern, I still fancy CodeBuild to deploy kubernetes especially Amazon EKS.

**Comment by BenICE** [comment]
Vote for this as well...I cannot figure out what is wrong.
> fork/exec /var/task/bootstrap: no such file or directory
Boostrap is in the zip (if I do not include it, I get another error; I can revoke rights, I get another error)...so what is wrong? Any ideas?

**Comment by Mistawes** [comment]
Lost a day trying to get this working, just going to build my own bash layer to avoid these constant issues.

I hit problems trying to use an existing layer (from us-east-1 in eu-west-1) as it doesn't list any available versions from CLI, or to build it myself using your instructions.

Hoping it's some day easier for people to use, as its just what I'm looking for, but gkrizek has it far better documented.
