### ISSUE TITLE
How I do run the python client? 

### ISSUE THREAD

**Issue by rohinrohin** [aws-samples/aws-lambda-layer-kubectl#14]
Is it possible to use the python kubernetes client on this layer to deploy programmatically?

If possible can you give me a brief of what I would need to do.

**Comment by pahud** [comment]
This layer is primarily for custom runtime as it provides the binary in the layer.

If you are using Python I think you should try [kubernetes-client/python](https://github.com/kubernetes-client/python) and probably generate your kubeconfig in python like [this](https://stackoverflow.com/questions/54953190/amazon-eks-generate-update-kubeconfig-via-python-script) before[ load_kube_config](https://github.com/kubernetes-client/python-base/blob/a2d1024524de78b62e5f9aa72d34cb9ea9de2b97/config/kube_config.py#L643) by providing the kubeconfig location.

I haven't tried it yet but it should work.

**Comment by pahud** [comment]
I will create a sample for you in the next few days.

**Comment by rohinwork** [comment]
@pahud thanks for the resources. This looks good 👍

**Comment by pahud** [comment]
@rohinrohin  Hey I've built a sample for you

https://github.com/pahud/eks-lambda-py

and my tweet

https://twitter.com/pahudnet/status/1201881237671104512
