### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by lucheeseng827** [aws-samples/aws-lambda-layer-kubectl#16]
I have managed to push the lambda function,  I did add the lambda arn role on aws-auth of eks configmap(the arn arn:aws:iam::XXXXXX:role/LambdaEKSAdminRole of the lambda and it has attached lambda role to it),
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeTags",
                "eks:DescribeCluster"
            ],
            "Resource": "*"
        }
    ]
}`

 but I am seeing the following error as I am trying to trigger Nginx.yaml invoke command 

`INPUT_YAML=nginx.yaml make invoke
base64: invalid option -- w
Usage:	base64 [-hvDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
START RequestId: 6558888a-5aed-4f41-9d62-7c078843b6cc Version: $LATEST
END RequestId: 6558888a-5aed-4f41-9d62-7c078843b6cc
REPORT RequestId: 6558888a-5aed-4f41-9d62-7c078843b6cc	Duration: 30.39 ms	Billed Duration: 100 ms	Memory Size: 512 MB	Max Memory Used: 12 MB
RequestId: 6558888a-5aed-4f41-9d62-7c078843b6cc Error: &{0xc000092240 map[invoke_id:6558888a-5aed-4f41-9d62-7c078843b6cc sandbox_id:0] 2019-12-16 05:25:47.793431627 +0000 UTC m=+4.146706490 panic <nil> Runtime failed to start: fork/exec /var/task/bootstrap: permission denied <nil> }
Runtime.ExitError`

**Comment by lucheeseng827** [comment]
I did `chmod 775 -R .`  and it seemed okay now

**Comment by corpulent** [comment]
@lucheeseng827 where did you add that line exactly?  I am adding it in the beginning of main.sh and I still get that error.

```
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: e122bf2d-a48d-40d3-980c-9e78a588aabe Error: &{0xc00005e2a0 map[invoke_id:e122bf2d-a48d-40d3-980c-9e78a588aabe sandbox_id:0] 2019-12-24 21:53:48.836604844 +0000 UTC m=+0.887596297 panic <nil> Runtime failed to start: fork/exec /var/task/bootstrap: permission denied <nil> }"
}
```

**Comment by lucheeseng827** [comment]
you will need to change the permission for the files first, then change at the bootstrap and main.sh(I have added [](https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/master/main.sh#L27) like `kubectl apply -f "/tmp/$FILE_YAML"`
[https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/master/bootstrap#L33](url)
with `  export FILE_YAML=$(echo "$EVENT_DATA" | jq --raw-output '.responsePayload.deployment_file')

  aws s3 cp s3://bucket_name/$FILE_YAML /tmp/$FILE_YAML`

**Comment by lucheeseng827** [comment]
Unless you are referring the `aws-auth.yaml` (the yaml that gives permission of your lambda to run on eks), that would look like this
`apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::xxxxxxx:role/test-eks-c-
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: **arn:aws:iam::xxxxxxxx:role/LambdaEKSAdminRole**
      username: LambdaEKSAdminRole
      groups:
        - system:masters
    - rolearn: arn:aws:iam::xxxxxxx:user/eks-serviceuser
      username: eks-serviceuser
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth`

**Comment by corpulent** [comment]
> you will need to change the permission for the files first, then change at the bootstrap and main.sh(I have added [(https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/master/main.sh#L27](url) like `kubectl apply -f "/tmp/$FILE_YAML"`
> [https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/master/bootstrap#L33](url)
> with
> 
> ```
> #this is the command where I copy file into the lambda /tmp path and kubectl apply them
> export FILE_YAML=$(echo "$EVENT_DATA" | jq --raw-output '.responsePayload.deployment_file')
> aws s3 cp s3://bucket_name/$FILE_YAML /tmp/$FILE_YAML
> ```

@lucheeseng827 My lambda permissions are fine.  The issue was that the function files which are created after running `make func-prep` where not executable files.  So what ended up working is deploying the layer from scratch (the README is missing the `make sam-layer-package` step btw,  I will open a PR).  And then:

```
make func-prep
chmod -R +x func.d/
CLUSTER_NAME=<YOUR_CLUSTER_NAME> make sam-package sam-deploy
```

Thanks for your help with this.
