### ISSUE TITLE
Make it compatible with other runtimes

### ISSUE THREAD

**Issue by hoegertn** [aws-samples/aws-lambda-layer-kubectl#17]
Are there plans to make this layer compatible with existing runtimes?

I just want to include this layer into the Python runtime and run `kubectl` commands as a subprocess without bootstrap files and custom runtimes.

**Comment by pahud** [comment]
Hi @hoegertn 

This layer is designed for custom runtime but is also compatible with python runtime.

If you check aws-eks construct lib from AWS CDK, the **KubectlProvider** under the hood is actually leveraging this layer in python runtime to create kubernetes and helm resources in AWS CDK.

https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-eks/lib/kubectl-handler

**Comment by hoegertn** [comment]
Thanks for the link, that is exactly what I want to do.

But https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/master/sam-layer.yaml#L30 sais only provided runtimes are supported and I could not select this layer when creating the Lambda function manually.

**Comment by pahud** [comment]
Hi @hoegertn 

Thanks for bringing this up.

Looks like we can only specify up to 5 `CompatibleRuntimes` in this array and we can't specify all of them. 

So I prefer to leave it as is and if we need to specify python or any other runtime manually in the lambda console we just need enter the full layer version ARN like this

<img width="922" alt="圖片" src="https://user-images.githubusercontent.com/278432/73419101-e2d4c780-4358-11ea-8867-1746f3f24e5c.png">

<img width="1180" alt="圖片" src="https://user-images.githubusercontent.com/278432/73418900-38f53b00-4358-11ea-9a62-4b441f95a77b.png">

**Comment by hoegertn** [comment]
Perfect, if this is possible this is fine for me.

**Comment by pahud** [comment]
Gerat! And I have another Lambda sample in Python that authenticates against Amazon EKS to call native kubernetes API such as list pods without using the kubectl client

ICYMI

https://github.com/pahud/eks-lambda-py

FYR
