### ISSUE TITLE
support custom SAR APP Name

### ISSUE THREAD

**Issue by pahud** [aws-samples/aws-lambda-layer-kubectl#21]
https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/647dffca68cc25151c1122fe4e1bd35ef6e56948/sam-layer.yaml#L10

we should provide an option in the Makefile to customize the SAR App name.

**Comment by zxkane** [comment]
Yes, the build env `SAR_APP_NAME` is not honored as custom the SAR app name.
