### ISSUE TITLE
lambda-layer-kubectl does not have a version 1.13.7

### ISSUE THREAD

**Issue by orangewise** [aws-samples/aws-lambda-layer-kubectl#23]
Hi,

Im now getting this error while deploying a k8s cluster using the cdk:

Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [kubectllayer8C2542BCBF2B4DFEB765E181FD30A9A0617C4ADA] is invalid. Application arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-kubectl does not have a version 1.13.7

**Comment by orangewise** [comment]
Upgraded to cdk version `1.27.0` and it works again :)

**Comment by pahud** [comment]
Hi @orangewise , can you let me know which region you were deploying to?

I am trying to investigate this issue.

**Comment by orangewise** [comment]
Yes, I’m deploying to eu-west-1

**Comment by pahud** [comment]
> Yes, I’m deploying to eu-west-1

I was trying to deploy `1.13.7` in `eu-west-1` and it works. Happy to see you have been running CDK 1.27.0 with no errors.

<img width="1164" alt="圖片" src="https://user-images.githubusercontent.com/278432/76303849-5a552980-62fd-11ea-822a-4e502648c1c7.png">

If you happen to encounter the same error or similar ones, please let me know.

Thanks.
