### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by kencieszykowski** [aws-samples/aws-lambda-layer-kubectl#29]
Appreciate the effort on this; but have run into a few issues with following the documentation:

1) On the make sam-deploy step, the IAM role fails creation since it Lambda is not allowed to assume it.  

`CREATE_FAILED                     AWS::Lambda::Function             Func                              The role defined for the
                                                                                                      function cannot be assumed by
                                                                                                      Lambda. (Service:
                                                                                                      AWSLambdaInternal; Status Code:
                                                                                                      400; Error Code:
                                                                                                      InvalidParameterValueException;
                                                                                                      Request ID: 6e605934-b3d0-43d1-
                                                                                                      b583-ad5d5313933f)
ROLLBACK_IN_PROGRESS              AWS::CloudFormation::Stack        eks-kubectl-stack                 The following resource(s)
                                                                                                      failed to create: [Func]. .
                                                                                                      Rollback requested by user.`

To get around that, I specified a previously created role in the sam.yaml with proper permissions.

2) Once it deployed, was hit with this error:
`RequestId: 82b98cc4-17df-40bc-9245-0548d75ea51d Error: &{0xc0000b4070 map[invoke_id:82b98cc4-17df-40bc-9245-0548d75ea51d sandbox_id:0] 2020-04-30 19:58:19.627306526 +0000 UTC m=+0.020718995 panic <nil> Runtime failed to start: fork/exec /var/task/bootstrap: permission denied <nil> <nil> }
Runtime.ExitError`

It seems that func.d did not give bootstrap the proper permissions.  I chmod'd the bootstrap and main.sh just to be sure, and it progressed to the next error:

`2020-04-30T20:01:42.624Z ddb418fd-a9b2-463c-b0fa-57cdf883b47f Task timed out after 10.01 seconds`

Any help would be appreciated; running commands as an Administrator in AWS with full permissions sets.

**Comment by pahud** [comment]
Thanks feedback. Will look into it today.

**Comment by pahud** [comment]
I will revamp the sample with AWS CDK to simply the process

https://github.com/aws-samples/aws-lambda-layer-kubectl/issues/30

**Comment by pahud** [comment]
I've revamped the deployment sample with AWS CDK. I believe it would be simpler than SAM.

https://github.com/aws-samples/aws-lambda-layer-kubectl#deploy-the-sample-stack-with-aws-cdk
