### ISSUE TITLE
Can not connect to private EKS cluster

### ISSUE THREAD

**Issue by shrivastavshubham34** [aws-samples/aws-lambda-layer-kubectl#32]
I'm trying to access a private EKS cluster already deployed.

Following the readme instructions, I pulled the SARs, but was not sure how to use it.
So, I pulled the repo and had to build it manually based on the existing CDK application.
[https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/master/cdk/README.md](url)

I made sure my handler function was using cluster_name as Environment but still I'm getting a time-out after 30 seconds and not sure how to debug this.

**Comment by pahud** [comment]
Thanks for the report. It's very important to support this scenario. I will look into it in the next 1 or 2 days.

related to https://github.com/aws/aws-cdk/issues/7972

**Comment by shrivastavshubham34** [comment]
I have assigned a VPC to this lambda function, along with all subnets and a security group with all VPC access.
However, to connect to EKS I tried to add relevant security groups that I used when I tested EKS connectivity from an EC2 instance within the same VPC.
Lambda function, however, keeps timing out.

[https://stackoverflow.com/questions/61789276/how-can-i-connect-to-private-eks-endpoint-from-a-lambda-function](url)

**Comment by pahud** [comment]
Yes I noticed that. I will get it sorted and provide a working sample with required fix if any.

**Comment by shrivastavshubham34** [comment]
Meanwhile, can you suggest a workaround, from a lambda function's perspective?

**Comment by pahud** [comment]
Not at this moment. But I guess the Lambda function will need to share the same security with the eks control plane. I'd try explore this way.

**Comment by pahud** [comment]
@shrivastavshubham34 

OK. It works in my environment now

If your lambda function with kubectl lambda layer will need connect to the eks private endpoint, you need:

1. enable Lambda function with vpc support and associate with the same VPC with the eks cluster
2. attach the EKS `Cluster Security Group` on the Lambda function

In your EKS console
<img width="1548" alt="圖片" src="https://user-images.githubusercontent.com/278432/81930378-16dbac00-961b-11ea-8231-2d3b418755db.png">

In your Lambda function console
<img width="1720" alt="圖片" src="https://user-images.githubusercontent.com/278432/81930629-691ccd00-961b-11ea-8c18-ae985e2626e0.png">

And `kubectl get no` shoudl return the node list successfully
<img width="1200" alt="圖片" src="https://user-images.githubusercontent.com/278432/81930890-c87add00-961b-11ea-963a-4b5e74e4ebf7.png">

Let me know if it works in your environment.

**Comment by pahud** [comment]
Just added some notes in the README FYR

https://github.com/aws-samples/aws-lambda-layer-kubectl/tree/master/cdk#amazon-eks-private-endpoint-support

**Comment by shrivastavshubham34** [comment]
Hey, thanks for the help. Yes, I was able to make it work using your guide.

Although, the Lambda Role could not connect to my cluster.
Kept getting permission denied.
`error: You must be logged in to the server (Unauthorized)`

To solve this:
1. I attached an Inline Policy to my role.

```yaml
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::1234567890123:role/newrole"
        }
    ]
}
```

2. Then modified the **configmap/aws-auth** removing the lambda role with _arn:aws:iam::1234567890123:role/newrole_.

3. Modified the update kubeconfig with
```shell
    aws eks update-kubeconfig --name "$1" --role-arn "$2" --kubeconfig /tmp/kubeconfig
``` 
And added role arn:aws:iam::1234567890123:role/newrole.

This made me connect.

Still not sure why I had to assume a role.
But, I'm able to connect to EKS now so I'll close this issue.

Thanks again, @pahud

**Comment by Chetan496** [comment]
@shrivastavshubham34 your suggestion worked for me. In my case, the EKS worker nodes are in private subnet, the API server endpoint is public. Yet, I was also facing the same issue. Followed the suggestion mentioned by you, and it worked,
