### ISSUE TITLE
Suggestions for documentation

### ISSUE THREAD

**Issue by proca-ainq** [aws-samples/aws-lambda-layer-kubectl#36]
Hi - thanks a lot for this project.  I was able to get this to work with a NodeJS lambda using `require('child_process')`, but I had to do 2 additional things.

1. I had to manually build the AWS CLI from scratch using https://github.com/aws-samples/aws-lambda-layer-awscli so that it worked with nodejs runtime and replace the /opt/awscli folder in `aws-lambda-layer-kubectl` with the output from the manual build
2. I had to add --role-arn to the `aws eks update-kubeconfig` command and an extra clause in the IAM role to assume the role. 

I'm not an expert by any means, but I spent a day getting it to work, so I thought I'd share in case you wanted to modify the docs to mention any of this.  

Thanks again!

**Comment by pahud** [comment]
Thanks for your feedback. Yes, I will improve the document in the next few days to ensure people can always build this from scratch.

**Comment by KorvinSzanto** [comment]
I tried getting this working with the a nodejs runtime and I wasn't able to do it even with copying out the awscli directory from a manually build aws-lambda-layer-awscli layer.zip build with their node instructions. @proca-ainq more information on what you did for your step 1 would be much appreciated!

**Comment by proca-ainq** [comment]
@KorvinSzanto  Did you see the section of the other git repo labeled 'Node10 and Node12 AWS Lambda runtime support'?  You have to follow those instructions.

**Comment by proca-ainq** [comment]
To be clear, I'm referring to https://github.com/aws-samples/aws-lambda-layer-awscli

**Comment by KorvinSzanto** [comment]
Yes, I built the awscli layer with the node specific make instructions there and then copied out the awscli directory from the built layer.zip

**Comment by proca-ainq** [comment]
I might be able to provide more info if you can elaborate on what isn't working.  A month is a long time and I can't remember the exact things I did.  

I will say that having a lambda with EKS access has been extremely useful for us.  The only downside is that it's a vulnerability, so I had to add a bunch of protections so the lambda isn't misused.
