### ISSUE TITLE
"libpython2.7.so.1.0: cannot open shared object file: No such file or directory" when using provided.al2 runtime

### ISSUE THREAD

**Issue by KorvinSzanto** [aws-samples/aws-lambda-layer-kubectl#37]
I'm trying to use this layer with the `provided.al2` runtime and I'm running into this error when the AWS CLI gets used:
```
 [ERROR] /opt/awscli/bin/python: error while loading shared libraries:
         libpython2.7.so.1.0: cannot open shared object file: No such file or
         directory
```
Is this something I can get around easily?

**Comment by zxkane** [comment]
Are you using runtime `python 3.8`? using `python 3.7` should work.

**Comment by KorvinSzanto** [comment]
@zxkane no I'm using `provided.al2` as the runtime. I've also tried using the node 12 runtime but I get the same error. Unfortunately using python 3.7 runtime likely won't work for what I'm trying to do.

**Comment by pahud** [comment]
Hi @KorvinSzanto 

I am working on this PR https://github.com/aws-samples/aws-lambda-layer-kubectl/pull/38  for some major bumps.

From my testing with this PR it works great with both `custom runtime` and `custom runtime on Amazon Linux 2`.

Can you checkout this [branch](https://github.com/pahud/aws-lambda-layer-kubectl/tree/support-projen) from this PR , build and publish your own layer and test it again?
