### ISSUE TITLE
Update to newest kubectl version

### ISSUE THREAD

**Issue by edisongustavo** [aws-samples/aws-lambda-layer-kubectl#4]
Hello, it would be great if we could get the latest `kubectl` version in the layer.

Thanks

**Comment by pahud** [comment]
Hi

At this moment, we'll stick to the latest version of `kubectl` provided from Amazon EKS document, which is `1.12.7` at this moment
https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html

If you need to use the latest kubectl binary, just edit the Dockerfile and replace it with the latest binary URL.
https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/525d7d3f24152a2403035b7b8917277f671417c7/Dockerfile#L22

And just follow the build from scratch tutorial here
https://github.com/aws-samples/aws-lambda-layer-kubectl#option-2---build-from-scratch

You should be able to build your own layer with the latest version of kubectl binary.

**Comment by pahud** [comment]
Just FYI. We support 1.13.7 today.
