### ISSUE TITLE
Add eksctl

### ISSUE THREAD

**Issue by faermanj** [aws-samples/aws-lambda-layer-kubectl#42]
Also featuring eksctl in this lambda layer would be quite helpful.
It would allow us to add the required RBAC mapping by CLI instead of manually adding it to the configMap yaml.
See: https://www.eksworkshop.com/beginner/091_iam-groups/configure-aws-auth/

**Comment by pahud** [comment]
Thank you for your feedback. As we are planning to refactor this repo we will not add anything into the layer but you will be allowed to customize it yourself. See https://github.com/aws-samples/aws-lambda-layer-kubectl/issues/43 for more details.
