### ISSUE TITLE
can "aws-lambda-layer-kubectl" deploy "Kubernetes custom resource definitions" & "IAM OIDC provider" for eks?

### ISSUE THREAD

**Issue by yanmin950122** [aws-samples/aws-lambda-layer-kubectl#59]
I am using cdk to build an appmesh cluster based on eks, followed : https://github.com/aws/eks-charts/tree/master/stable/appmesh-controller#upgrade. About 
```
Install the App Mesh CRDs:
kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"
```
and
```
Enable IAM OIDC provider
eksctl utils associate-iam-oidc-provider --region=$AWS_REGION \
    --cluster=$CLUSTER_NAME \
    --approve
```
this kubectl&eksctl command，I did not find the corresponding command in the cdk. Could I use "ws-lambda-layer-kubectl" to resolve it? What should I do?

**Comment by pahud** [comment]
For OIDC or service account with Amazon EKS and AWS CDK, check this README and code snippets here
https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-eks#service-accounts

You can run `kubectl` with this layer from Lambda function, however, you need write a custom resource for that. For example, you can create your `KubectlProvider` like [this](https://github.com/aws/aws-cdk/blob/124a7a1c20981c72bfdce0c857c87c46c6cb5f51/packages/%40aws-cdk/aws-eks/lib/kubectl-provider.ts#L22) in AWS CDK so you can instantiate this provider and build your custom resource like [this](https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-eks/lib/helm-chart.ts#L98-L128).

Alternatively, you can consider using [pahud/cdk-lambda-bash](https://github.com/pahud/cdk-lambda-bash) to run any `kubectl` commands in shell script.
