### ISSUE TITLE
Broken link to configmap-sar.yaml

### ISSUE THREAD

**Issue by swoldemi** [aws-samples/aws-lambda-layer-kubectl#8]
In the README for the update-configmap sample: https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/master/samples/update-configmap/README.md

The link to the configmap-sar.yaml cloudformation template is broken: https://github.com/pahud/eks-templates/blob/master/cloudformation/configmap-sar.yaml

Should https://github.com/aws-samples/amazon-eks-refarch-cloudformation/blob/master/cloudformation/configmap-sar.yaml be the new link?

**Comment by pahud** [comment]
https://github.com/aws-samples/aws-lambda-layer-kubectl/commit/d5e2dff29303c285b20005211abca28969a7042c fixed. Thanks a lot!
